import mongoose, { Document, mquery } from 'mongoose';

declare module 'cachegoose' {

	declare function cachegoose(mongoose: mongoose, cacheOptions: any): void;

	declare namespace cachegoose {
		function clearCache(customKey: any, cb: any): void;
	}

	/** Declaration file generated by dts-gen */
	export = cachegoose;
}

declare module 'mongoose' {
	// eslint-disable-next-line @typescript-eslint/class-name-casing
	interface DocumentQuery<T, DocType extends Document, QueryHelpers = {}> {
		cache(ttl: number = 60, customKey: string = ''): this
		cache(customKey: string = ''): this
		cache(ttl: number = 60): this
	}
}

